process resolver_v4-check {
        run /usr/bin/python3 -m exabgp healthcheck \
                --cmd "/opt/anycast-resolver/bin/healthcheck" \
                --interval 1 \
                --no-syslog \
                --rise 30 \
                --fall 3 \
                --disable /opt/anycast-resolver/disable_resolver \
                --ip 10.0.0.53/32 \
                --up-metric 0 \
                --large-community 65053:0:53 \
                --down-metric 10000 \
                --disabled-metric 10000 \
                --next-hop 192.168.1.2 \
                --up-execute "/opt/anycast-resolver/bin/event-handler UP" \
                --down-execute "/opt/anycast-resolver/bin/event-handler DOWN" \
                --disabled-execute "/opt/anycast-resolver/bin/event-handler DISABLED";
        encoder text;
}
# Jika ingin withdraw prefix ketika healthcheck failed dan disable gunakan parameter --withdraw-on-down


neighbor 192.168.1.1 {
        router-id 192.168.1.2;
        local-address 192.168.1.2;
        local-as 65053;
        peer-as 65053;
        hold-time 31;

        family {
                ipv4 unicast;
        }

        api anycast_v4 {
                processes [ resolver_v4-check ];
        }
}
