# ==============================================================================
# ANYCAST DNS CONFIGURATION FILE
# ==============================================================================

# Network Settings
RESOLVER_IP="10.0.0.53"
LOG_TAG="anycast-resolver"


# --- Healthcheck Settings ---
# List domain yang akan di-query untuk tes koneksi DNS
CHECK_DOMAINS=("google.com" "facebook.com" "cloudflare.com" "amazon.com" "apple.com")

# Batas minimum domain yang harus sukses resolve agar node dianggap UP
CHECK_THRESHOLD=3       

# Timeout dalam detik untuk setiap kueri dig
CHECK_TIMEOUT=1

# Jumlah percobaan kueri ke setiap domain
CHECK_TRIES=1

# --- Event Commands ---
# Perintah yang dijalankan saat status berubah, contoh jika DNS server menggunakan  unbound
#ON_UP="/opt/anycast-resolver/scripts/unbound-flush-cache.sh"
#ON_DOWN="/opt/anycast-resolver/scripts/unbound-flush-cache.sh"
#ON_DISABLED="/opt/anycast-resolver/scripts/unbound-flush-cache.sh"
